# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - sociapptest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install dependencies and build the front-end
      - name: npm install, build, and test
        working-directory: ./front
        run: |
          npm install
          npm run build --if-present

      # Zip the build folder for deployment
      - name: Zip artifact for deployment
        working-directory: ./front/build
        run: zip -r ../../release.zip .

      # Upload the zipped artifact for the deploy job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: front-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      # Download the artifact created during the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: front-app

      # Unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6D2A4A45FD3C403F8BA171661D903826 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D68C83750D16409787D4EEF81B8D89A3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_27C6F838B0AE43AEBC27CC502B95C834 }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sociapptest'
          slot-name: 'Production'
          package: ./ # Deploy from the current directory
